### ISSUE TITLE
Container Runtime integration

### ISSUE THREAD

**Issue by decke** [sadaszewski/focker#3]
Are there any plans to integrate focker with any of the existing container runtimes? From what I know many people hope for kubernetes support on FreeBSD so focker would need to integrate with one of the existing container runtimes that are supported by kubernetes already unless someone wants to create yet another container runtime.

From the kubernetes docs currently supported container runtimes are:
* docker
* CRI-O
* containerd
* frakti

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by sadaszewski** [comment]
No such integration is planned and it wouldn't necessarily be easy, given
that the existing runtimes are Linux-centric and not even written in
Python. Go seems to be the dominant language in this area. However, simply
extending one of the runtimes with support for FreeBSD, using Focker as a
loose reference (since it supports many notions from the OCI runtime-spec)
might be an option. However, I wouldn't undertake it on my own. I have an
interest in this happening and in the Kubernetes support for FreeBSD. I
could envisage being part of a working group but it is too much effort for
my schedule alone.

**Comment by jgod** [comment]
Someone started on it https://samuel.karp.dev/blog/2021/03/runj-a-new-oci-runtime-for-freebsd-jails/

**Comment by sadaszewski** [comment]
Sounds great. Samuel seems to be working on container technologies on his day job so he is definitely better equipped to deal with such a project. I will stick to Focker as I know it like the back of my hand and I think for quite some time runj will not be able to do anything for me that Focker can't. On the other hand, I think Focker can essentially generate root filesystems for runj so they could even be complementary to some extent. It should suffice to dump any Focker image into .txz and use the runj demo oci-image --input *.txz command. Would be interesting to hear from someone who tries.

**Comment by sadaszewski** [comment]
Closing. No plans to integrate with Container Runtimes.
