### ISSUE TITLE
What's needed next?

### ISSUE THREAD

**Issue by jgod** [sadaszewski/focker#6]
Thanks for this project.
My [first post](https://forums.freebsd.org/threads/docker-is-dead.69955/post-451755) on the forums, one year ago, was about this very thing.

Perhaps you could add a short list or roadmap of what needs help.
Haven't sat down to use this yet.

**Comment by sadaszewski** [comment]
Hi @jgod, thanks for the kind words. TBH the way it is now is more or less sufficient for myself and I believe the next steps should be community driven. I have read many comments on the forums mentioning that Focker is not an option for some people because it uses Python. Perhaps a rewrite in Go or C++ should be - albeit ambitious - the first step? Otherwise, perhaps a registry mechanism? I don't need it personally but it is a prominent part of the Docker ecosystem. Perhaps more explicit support for VIMAGE/VNET? Perhaps a change of name? It is unfortunate that apparently that was some silly movie about a family called Fockers. From my PoV, the name originates from FreeBSD + Docker. No plans yet from my side. I would be happy to be an ambassador of whatever effort the community deems most important but I would need some people willing to work on this together.

**Comment by sadaszewski** [comment]
I have a clearer vision now that I have released Focker 2.0, the next step is to move in the "Code as Infrastructure" direction, like in Kubernetes.
